# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]

jobs:
     
  Tests:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
      
    - name: Test with Gradle
      run: gradle test
      
  build:
    needs: [Tests]
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
     
    - name: Build with Gradle
      run: gradle build -x test
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1  
      with:
        name: user-service

   
        
